// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIlze91kuhGpeh6ovkcOFeTEUo2rJwO_4',
    appId: '1:254604799297:web:5959954a355f69323dc5c0',
    messagingSenderId: '254604799297',
    projectId: 'bookia-eda59',
    authDomain: 'bookia-eda59.firebaseapp.com',
    storageBucket: 'bookia-eda59.appspot.com',
    measurementId: 'G-NF0XKT7N1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmYSYTXCSNCTB1UfN9qDOz3h9BgUy9OA',
    appId: '1:254604799297:android:043ca6a5d9f6852c3dc5c0',
    messagingSenderId: '254604799297',
    projectId: 'bookia-eda59',
    storageBucket: 'bookia-eda59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAijjk3HBYa0ztjMZ45GkyOgGM6V9vZ7Q',
    appId: '1:254604799297:ios:956c380bae4535633dc5c0',
    messagingSenderId: '254604799297',
    projectId: 'bookia-eda59',
    storageBucket: 'bookia-eda59.appspot.com',
    iosBundleId: 'com.example.bookiaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAijjk3HBYa0ztjMZ45GkyOgGM6V9vZ7Q',
    appId: '1:254604799297:ios:956c380bae4535633dc5c0',
    messagingSenderId: '254604799297',
    projectId: 'bookia-eda59',
    storageBucket: 'bookia-eda59.appspot.com',
    iosBundleId: 'com.example.bookiaStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIlze91kuhGpeh6ovkcOFeTEUo2rJwO_4',
    appId: '1:254604799297:web:ac85089ff2c50da73dc5c0',
    messagingSenderId: '254604799297',
    projectId: 'bookia-eda59',
    authDomain: 'bookia-eda59.firebaseapp.com',
    storageBucket: 'bookia-eda59.appspot.com',
    measurementId: 'G-GMBF4LHEBY',
  );
}
